### ISSUE TITLE
Traceback (most recent call last):   File "hash.py", line 173, in <module>                                                                                         miner(file)                                                                                                               File "hash.py", line 144, in miner                                                                                            for line in f:                                                                                                            File "/usr/lib/python3.7/codecs.py", line 322, in decode                                                                      (result, consumed) = self._buffer_decode(data, self.errors, final)                                                      UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 4: invalid start byte 

### ISSUE THREAD

**Issue by cd6629** [s0md3v/Hash-Buster#30]
I ran `python3 hash.py -f`

A relevant suggestion from [this thread](https://stackoverflow.com/questions/42339876/error-unicodedecodeerror-utf-8-codec-cant-decode-byte-0xff-in-position-0-in) was already implemented in the code.

**Comment by Bigjango13** [comment]
Seems like you are running it on a image or some other binary file format.
